version: '3.9'
services:
  optfx:
    restart: always
    image: ichiharanaruki/optfx:latest
    container_name: 'optfx'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./:/workspace
    shm_size: 4gb
    ulimits:
      memlock: -1
      stack: 67108864
    environment:
      - DISPLAY=host.docker.internal:0.0
    environment:
      TZ: 'Asia/Tokyo'
