name: Run pytest
on: [push]

jobs:
  pytest:
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Login to Docker
          uses: docker/login-action@v1
          with:
            registry: docker.io
            username: ichiharanaruki
            password: ${{ secrets.DOCKER_IO_TOKEN }}
        - name: Set up Docker
          run: |
            docker pull ichiharanaruki/optfx:latest
            docker-compose up -d
        - name: Run test
          run: docker-compose run -T optfx pytest /workspace/test
